table 'Acrescentar - ID Transação Shopify'
	lineageTag: 9cb5e33d-b83e-492a-a052-71b3bc096fb4

	column 'Transaction: ID'
		dataType: int64
		formatString: 0
		lineageTag: 33ad9b55-c012-4796-9d81-f5f4ffd8aaa3
		summarizeBy: count
		sourceColumn: Transaction: ID

		annotation SummarizationSetBy = Automatic

	column 'Transaction: Authorization'
		dataType: string
		lineageTag: 69cc7df7-63b8-472f-ba10-aa6756ac02c8
		summarizeBy: none
		sourceColumn: Transaction: Authorization

		annotation SummarizationSetBy = Automatic

	column 'Transaction: Payment ID'
		dataType: string
		lineageTag: 143949fb-e9fb-4c01-b761-9f66f8020745
		summarizeBy: none
		sourceColumn: Transaction: Payment ID

		annotation SummarizationSetBy = Automatic

	column 'Transaction: Gateway'
		dataType: string
		lineageTag: b94efd31-d4cb-4d3d-9b47-53af176dd61c
		summarizeBy: none
		sourceColumn: Transaction: Gateway

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 3fa9883c-2c89-4942-bc27-11ceb9f7ba43
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Number
		dataType: int64
		formatString: 0
		lineageTag: 29ce7494-3018-4710-ab5d-b5ffe698cf8b
		summarizeBy: sum
		sourceColumn: Number

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: string
		lineageTag: c9045e55-1270-4e11-b5dc-6d41b1c138e1
		summarizeBy: none
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

	column Orders_1
		dataType: string
		lineageTag: 519a41e6-cf3d-40ed-a35b-1cd725d1dcdf
		summarizeBy: none
		sourceColumn: Orders_1

		annotation SummarizationSetBy = Automatic

	column Sheet
		dataType: string
		lineageTag: 2d0f0031-db0d-4126-b615-b7421621d908
		summarizeBy: none
		sourceColumn: Sheet

		annotation SummarizationSetBy = Automatic

	column false
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cb08e781-261f-4f76-8a18-7a47eaedf210
		summarizeBy: none
		sourceColumn: false

		annotation SummarizationSetBy = Automatic

	partition 'Acrescentar - ID Transação Shopify' = m
		mode: import
		queryGroup: Marketplaces\Repasses\Shopify
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://maxiferramentasltda.sharepoint.com/sites/PowerBi/Documentos%20Compartilhados/Planilhas%20-%20BI/Shopify%20-%20Last%202%20M.xlsx" ), null, true),
				    #"Data Expandido" = Table.ExpandTableColumn(Fonte, "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6"}, {"Data.Column1", "Data.Column2", "Data.Column3", "Data.Column4", "Data.Column5", "Data.Column6"}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Data Expandido", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Orders", type text}, {"Transaction: ID", Int64.Type}, {"Transaction: Authorization", type text}, {"Transaction: Payment ID", type text}, {"Transaction: Gateway", type text}, {"ID", Int64.Type}, {"Number", Int64.Type}, {"Orders_1", type text}, {"Sheet", type text}, {"false", type logical}}),
				    #"Consulta Acrescentada" = Table.Combine({#"Tipo Alterado", #"Shopify - Legado"})
				in
				    #"Consulta Acrescentada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

