table Braspag
	lineageTag: 4d707343-d218-48c4-9778-9a488b4ecdca

	column BraspagTransactionId
		dataType: string
		lineageTag: 88696014-5dec-42a0-ad0b-133768152a2b
		summarizeBy: none
		sourceColumn: BraspagTransactionId

		annotation SummarizationSetBy = Automatic

	column 'Data do Pedido'
		dataType: dateTime
		formatString: General Date
		lineageTag: 18324b69-74db-4bb9-8c29-39689bc1b686
		summarizeBy: none
		sourceColumn: Data do Pedido

		variation Variation
			isDefault
			relationship: ba931847-cb9d-4bcc-be3f-fec8385e79bc
			defaultHierarchy: LocalDateTable_c8314fb6-5201-4553-b9d1-6b606122e563.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Loja
		dataType: string
		lineageTag: 5aeb87e9-a30e-4c80-acca-4a61d193310b
		summarizeBy: none
		sourceColumn: Loja

		annotation SummarizationSetBy = Automatic

	column 'Numero do Pedido'
		dataType: string
		lineageTag: 0602c620-5a6e-4fd3-a7b9-fe38a34b10c3
		summarizeBy: none
		sourceColumn: Numero do Pedido

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: 58427773-94ea-4161-938f-f50bc390dc55
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column CPF/CNPJ
		dataType: string
		lineageTag: 1dbb0c8c-8e25-4565-9bb2-a2e787165b4e
		summarizeBy: none
		sourceColumn: CPF/CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Meio de Pagamento'
		dataType: string
		lineageTag: 79731d9d-1f23-480d-bb06-17deb35495ff
		summarizeBy: none
		sourceColumn: Tipo de Meio de Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Meio de Pagamento'
		dataType: string
		lineageTag: a19f351f-b195-419a-9b4e-21d4a72a9c64
		summarizeBy: none
		sourceColumn: Meio de Pagamento

		annotation SummarizationSetBy = Automatic

	column Parcelas
		dataType: string
		lineageTag: 53759b29-cc01-4565-b556-eaee97ee11a3
		summarizeBy: none
		sourceColumn: Parcelas

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: string
		lineageTag: ad9dba4b-b4a5-4c70-b028-c18c58ee5144
		summarizeBy: none
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 48ee21d2-708b-47f3-8604-d52babb20c8d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column NSU
		dataType: int64
		formatString: 0
		lineageTag: 6743505f-e720-4588-b526-642d7b437ddf
		summarizeBy: sum
		sourceColumn: NSU

		annotation SummarizationSetBy = Automatic

	column Moeda
		dataType: string
		lineageTag: e715a0ef-f2fc-4e96-885a-ee65a0948c90
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column País
		dataType: string
		lineageTag: 531f1bc3-56fe-4b36-aa9d-a97dcb321044
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column 'Numero do Cartão'
		dataType: string
		lineageTag: 96373eb1-c768-4d81-a864-e0b796b1b27b
		summarizeBy: none
		sourceColumn: Numero do Cartão

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: b06c83ba-4c93-413d-a5ad-796edb5f2411
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 4f965eb8-c218-49e8-8838-ecd36fb644e8
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column BraspagOrderId
		dataType: string
		lineageTag: 69a6d9fb-4d86-4910-93e1-2ccf7f4f64d1
		summarizeBy: none
		sourceColumn: BraspagOrderId

		annotation SummarizationSetBy = Automatic

	column 'Código de Autorização'
		dataType: string
		lineageTag: 501be8ec-284b-4924-b87a-992f6e7ed242
		summarizeBy: none
		sourceColumn: Código de Autorização

		annotation SummarizationSetBy = Automatic

	column Bandeira
		dataType: string
		lineageTag: c03e6e33-d328-4591-a562-89d48ec40f12
		summarizeBy: none
		sourceColumn: Bandeira

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Integração'
		dataType: string
		lineageTag: bdcd0174-b2cc-46e0-a1e6-b42c69f05884
		summarizeBy: none
		sourceColumn: Tipo de Integração

		annotation SummarizationSetBy = Automatic

	column 'Data do Pagamento'
		dataType: string
		lineageTag: c517057a-f12b-4018-a188-319557b55ec7
		summarizeBy: none
		sourceColumn: Data do Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Valor Capturado'
		dataType: string
		lineageTag: af3cba44-0c1e-4f44-836c-7d35daee2d4d
		summarizeBy: none
		sourceColumn: Valor Capturado

		annotation SummarizationSetBy = Automatic

	column 'Data do Cancelamento'
		dataType: string
		lineageTag: 1bf811e2-9a2c-4e89-bd1a-cc37b593c077
		summarizeBy: none
		sourceColumn: Data do Cancelamento

		annotation SummarizationSetBy = Automatic

	column 'Valor Cancelado'
		dataType: string
		lineageTag: 57af6bb4-2f7b-45c0-9ff0-86a76d0944e2
		summarizeBy: none
		sourceColumn: Valor Cancelado

		annotation SummarizationSetBy = Automatic

	column 'Código de Erro'
		dataType: string
		lineageTag: 59acbcfe-e111-4393-89ca-d6662805de4e
		summarizeBy: none
		sourceColumn: Código de Erro

		annotation SummarizationSetBy = Automatic

	column 'Mensagem de Erro'
		dataType: string
		lineageTag: 7dc58eb4-ccad-496a-b021-13832a144d02
		summarizeBy: none
		sourceColumn: Mensagem de Erro

		annotation SummarizationSetBy = Automatic

	column SentOrderId
		dataType: string
		lineageTag: c7c717cb-3e20-4c78-abe6-e7e1724ead2b
		summarizeBy: none
		sourceColumn: SentOrderId

		annotation SummarizationSetBy = Automatic

	column CardHolder
		dataType: string
		lineageTag: 396a5b15-c419-40c9-8193-bab687531e27
		summarizeBy: none
		sourceColumn: CardHolder

		annotation SummarizationSetBy = Automatic

	column Txid
		dataType: string
		lineageTag: 4d38b03f-d7d1-4f9d-ace6-963701b87aa4
		summarizeBy: none
		sourceColumn: Txid

		annotation SummarizationSetBy = Automatic

	column MerchantId
		dataType: string
		lineageTag: 3a1964ce-7710-4c0d-a2a4-ea9167e101e3
		summarizeBy: none
		sourceColumn: MerchantId

		annotation SummarizationSetBy = Automatic

	column 'ID da adquirente'
		dataType: string
		lineageTag: 6e186b31-f3f0-4dbe-992f-77e5a64e6f75
		summarizeBy: none
		sourceColumn: ID da adquirente

		annotation SummarizationSetBy = Automatic

	partition Braspag = m
		mode: import
		queryGroup: Marketplaces\Repasses\Shopify
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://maxiferramentasltda.sharepoint.com/sites/PowerBi/Documentos%20Compartilhados/Planilhas%20-%20BI/Braspag.xlsx"), null, true),
				    Plan1_Sheet = Fonte{[Item="Plan1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Plan1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"NSU", Int64.Type}, {"Data do Pedido", type datetime}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado",{{"Data do Pedido", Order.Descending}})
				in
				    #"Linhas Classificadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

