table Braspag
	lineageTag: 66c05811-258f-40b1-9810-8226860e145f

	column BraspagTransactionId
		dataType: string
		lineageTag: f8e95ff2-e715-4612-9e47-fff4cf538b61
		summarizeBy: none
		sourceColumn: BraspagTransactionId

		annotation SummarizationSetBy = Automatic

	column 'Data do Pedido'
		dataType: dateTime
		formatString: General Date
		lineageTag: a2fb407b-dd46-4fc1-abda-189dffd75698
		summarizeBy: none
		sourceColumn: Data do Pedido

		variation Variation
			isDefault
			relationship: d462488a-4b54-4474-8be4-7fb940ba461e
			defaultHierarchy: LocalDateTable_34919668-ad01-4a0d-890b-ed94311233f3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Loja
		dataType: string
		lineageTag: 87fbef81-476d-4964-a4fd-e34fe1d35c1e
		summarizeBy: none
		sourceColumn: Loja

		annotation SummarizationSetBy = Automatic

	column 'Numero do Pedido'
		dataType: string
		lineageTag: 723f2f97-bdfc-4656-8d16-689109ada949
		summarizeBy: none
		sourceColumn: Numero do Pedido

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: 4efd67cc-2871-4161-8240-7c4ccc73c111
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column CPF/CNPJ
		dataType: string
		lineageTag: 15749e18-22b6-46e0-b91c-cf8175d3997e
		summarizeBy: none
		sourceColumn: CPF/CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Meio de Pagamento'
		dataType: string
		lineageTag: 4e652f03-055a-4704-8fb1-20830037d76c
		summarizeBy: none
		sourceColumn: Tipo de Meio de Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Meio de Pagamento'
		dataType: string
		lineageTag: 7463424c-068d-44f7-9701-7a3cfdaad314
		summarizeBy: none
		sourceColumn: Meio de Pagamento

		annotation SummarizationSetBy = Automatic

	column Parcelas
		dataType: string
		lineageTag: 64674868-4220-47f7-bffc-ac17b82e30e2
		summarizeBy: none
		sourceColumn: Parcelas

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: string
		lineageTag: 5b64cf39-4be5-4279-b47b-2db0887d914e
		summarizeBy: none
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 84b9fe17-3010-48ac-80a3-2840409ce71b
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column NSU
		dataType: int64
		formatString: 0
		lineageTag: 3e7255af-0e7c-4b34-8d2b-b6cd004ecf54
		summarizeBy: sum
		sourceColumn: NSU

		annotation SummarizationSetBy = Automatic

	column Moeda
		dataType: string
		lineageTag: bb3cf0a4-b4ca-48cd-9eda-9060d81ed733
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column País
		dataType: string
		lineageTag: 108525e2-9f0a-4503-a24d-bee1a3f917dd
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column 'Numero do Cartão'
		dataType: string
		lineageTag: c80e4cd1-0e5b-4884-a3f8-cb6b39e35d19
		summarizeBy: none
		sourceColumn: Numero do Cartão

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: bce61a2a-142d-4d06-8dea-b4c9413c5b1d
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 72cbeceb-704c-471e-9fd1-a01c62740ca0
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column BraspagOrderId
		dataType: string
		lineageTag: a7269acb-9102-4310-a58e-06fb03c50ffe
		summarizeBy: none
		sourceColumn: BraspagOrderId

		annotation SummarizationSetBy = Automatic

	column 'Código de Autorização'
		dataType: string
		lineageTag: 934ccd47-0d8e-4d24-aec6-f2b03f261621
		summarizeBy: none
		sourceColumn: Código de Autorização

		annotation SummarizationSetBy = Automatic

	column Bandeira
		dataType: string
		lineageTag: 740beb58-0e32-4d31-9a0e-724e2188c7f9
		summarizeBy: none
		sourceColumn: Bandeira

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Integração'
		dataType: string
		lineageTag: e69e4e85-d69d-4a2d-8841-adecea182ac2
		summarizeBy: none
		sourceColumn: Tipo de Integração

		annotation SummarizationSetBy = Automatic

	column 'Data do Pagamento'
		dataType: string
		lineageTag: d3edd419-1a01-43d4-862d-fee23d3c737f
		summarizeBy: none
		sourceColumn: Data do Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Valor Capturado'
		dataType: string
		lineageTag: c0bdeea4-7fc8-4596-8dc8-07e1ee8f8485
		summarizeBy: none
		sourceColumn: Valor Capturado

		annotation SummarizationSetBy = Automatic

	column 'Data do Cancelamento'
		dataType: string
		lineageTag: b41d21a0-f4b2-4383-a2cb-c439a27f0426
		summarizeBy: none
		sourceColumn: Data do Cancelamento

		annotation SummarizationSetBy = Automatic

	column 'Valor Cancelado'
		dataType: string
		lineageTag: 52e7d79c-97cb-4405-85ca-9355621b4f99
		summarizeBy: none
		sourceColumn: Valor Cancelado

		annotation SummarizationSetBy = Automatic

	column 'Código de Erro'
		dataType: string
		lineageTag: d9cebb1b-d0ca-4ff9-b153-4d8afe9a94a6
		summarizeBy: none
		sourceColumn: Código de Erro

		annotation SummarizationSetBy = Automatic

	column 'Mensagem de Erro'
		dataType: string
		lineageTag: d0eb7387-04ad-478e-b89b-b18caccfe0ac
		summarizeBy: none
		sourceColumn: Mensagem de Erro

		annotation SummarizationSetBy = Automatic

	column SentOrderId
		dataType: string
		lineageTag: 72f68f97-c20d-4d28-ace5-9bfe63236b2e
		summarizeBy: none
		sourceColumn: SentOrderId

		annotation SummarizationSetBy = Automatic

	column CardHolder
		dataType: string
		lineageTag: 887943e3-da32-4765-bb14-57dfa552e286
		summarizeBy: none
		sourceColumn: CardHolder

		annotation SummarizationSetBy = Automatic

	column Txid
		dataType: string
		lineageTag: 1a0ad1be-0ff1-4fca-89de-3b9508cde983
		summarizeBy: none
		sourceColumn: Txid

		annotation SummarizationSetBy = Automatic

	column MerchantId
		dataType: string
		lineageTag: 67b8ad14-6507-4302-8fac-19a0ea610e2f
		summarizeBy: none
		sourceColumn: MerchantId

		annotation SummarizationSetBy = Automatic

	column 'ID da adquirente'
		dataType: string
		lineageTag: be63f313-994b-4385-9922-efc27c0ce8b0
		summarizeBy: none
		sourceColumn: ID da adquirente

		annotation SummarizationSetBy = Automatic

	partition Braspag = m
		mode: import
		queryGroup: Marketplaces\Repasses\Shopify
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://maxiferramentasltda.sharepoint.com/sites/PowerBi/Documentos%20Compartilhados/Planilhas%20-%20BI/Braspag.xlsx"), null, true),
				    Plan1_Sheet = Fonte{[Item="Plan1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Plan1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"NSU", Int64.Type}, {"Data do Pedido", type datetime}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado",{{"Data do Pedido", Order.Descending}})
				in
				    #"Linhas Classificadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

