table 'Cielo + Braspag'
	lineageTag: 1211bfd0-3db0-46a8-9015-776e94be98c9

	column 'Repasse MKT'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 79c49f14-8d14-4855-bee0-ee9fe4c41c17
		summarizeBy: sum
		sourceColumn: Repasse MKT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Status MKT'
		dataType: string
		lineageTag: 2a906b51-7ea2-4b1d-b5e3-1b6b07f3fcdf
		summarizeBy: none
		sourceColumn: Status MKT

		annotation SummarizationSetBy = Automatic

	column 'Pedido MKT'
		dataType: string
		lineageTag: 986f30ea-3a93-4d5d-b85a-c2e00ddcaf69
		summarizeBy: none
		sourceColumn: Pedido MKT

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: f987a62e-f2cc-4d3a-a3c6-2d68e4ce83c6
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	partition 'Cielo + Braspag' = m
		mode: import
		queryGroup: Marketplaces\Repasses\Shopify
		source =
				let
				    Fonte = Table.NestedJoin(#"Cielo shopify", {"NSU/DOC"}, Braspag, {"NSU"}, "Braspag", JoinKind.LeftOuter),
				    #"Braspag Expandido" = Table.ExpandTableColumn(Fonte, "Braspag", {"Numero do Pedido", "Status"}, {"Numero do Pedido", "Status"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Braspag Expandido", each ([Numero do Pedido] <> null)),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"NSU/DOC"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"Status", "Status MKT"}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Renomeadas", {"Numero do Pedido"}, Matrixfy, {"transaction_authorization"}, "Matrixfy", JoinKind.LeftOuter),
				    #"Matrixfy Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Matrixfy", {"order_number", "tags"}, {"order_number", "Tags"}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Matrixfy Expandido",{"Numero do Pedido"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Removidas1","#","",Replacer.ReplaceText,{"order_number"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Valor Substituído",{{"order_number", "Pedido MKT"}})
				in
				    #"Colunas Renomeadas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

