table Matrixfy
	lineageTag: 8a89081f-57eb-4128-84e8-f103f84a023d

	column id
		dataType: int64
		formatString: 0
		lineageTag: 1f986b44-b74a-4fe7-928b-0892608dc9e2
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column shopify_order_id
		dataType: string
		lineageTag: 583a2db8-d887-412e-9a4d-518cd8e78c82
		summarizeBy: none
		sourceColumn: shopify_order_id

		annotation SummarizationSetBy = Automatic

	column order_number
		dataType: string
		lineageTag: 4d941cb9-26cc-4446-bbcf-5ca8f5bb37b2
		summarizeBy: none
		sourceColumn: order_number

		annotation SummarizationSetBy = Automatic

	column created_at_shopify
		dataType: dateTime
		formatString: General Date
		lineageTag: 3d2d014c-89c2-4675-8571-05d91169564f
		summarizeBy: none
		sourceColumn: created_at_shopify

		variation Variation
			isDefault
			relationship: d07e14a4-8ee6-4ffc-85f9-31861d67f4dd
			defaultHierarchy: LocalDateTable_f28b5168-bd92-4033-886f-22ec988f3dfb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column imported_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 9dafdd9a-eb4d-4a0c-8269-923856ec8958
		summarizeBy: none
		sourceColumn: imported_at

		variation Variation
			isDefault
			relationship: 33a946cb-3b4f-44ec-b46b-a9e4a3e46a19
			defaultHierarchy: LocalDateTable_e61a7ba8-72bd-43bf-bded-f2c7312c495d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column transaction_authorization
		dataType: string
		lineageTag: 38505163-d8ba-4193-9dc9-125f794f519a
		summarizeBy: none
		sourceColumn: transaction_authorization

		annotation SummarizationSetBy = Automatic

	column transaction_payment_id
		dataType: string
		lineageTag: 51ecdd6b-5d46-45f6-b1fc-d383e4bf5a2b
		summarizeBy: none
		sourceColumn: transaction_payment_id

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: df0b88dd-858c-49c4-b0e0-185da4307fbe
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	partition Matrixfy = m
		mode: import
		queryGroup: Marketplaces\Repasses\Shopify
		source =
				let
				    BaseUrl  = "https://mxsdrojeuyuuokfxhjyb.supabase.co",
				    ApiKey   = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14c2Ryb2pldXl1dW9rZnhoanliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MTEwNzEsImV4cCI6MjA4MjM4NzA3MX0.loxFGXbJVk3xwSHb8U5STG6QxoISFtlB6qcQLxowRs8",
				    PageSize = 1000,
				    BuscarPagina = (Offset as number) as list =>
				        Json.Document(Web.Contents(BaseUrl, [
				            RelativePath = "rest/v1/shopify_pedidos_raw",
				            Headers      = [apikey = ApiKey, Authorization = "Bearer " & ApiKey],
				            Query        = [select="*", limit=Text.From(PageSize), offset=Text.From(Offset)]
				        ])),
				    TodasPaginas = List.Generate(
				        () => [Pagina = BuscarPagina(0), Offset = 0],
				        each List.Count([Pagina]) > 0,
				        each [Pagina = BuscarPagina([Offset] + PageSize), Offset = [Offset] + PageSize],
				        each [Pagina]
				    ),
				    TodosRegistros = List.Combine(TodasPaginas),
				    Tabela         = Table.FromList(TodosRegistros, Splitter.SplitByNothing(), {"Row"}),
				    Expandido = Table.ExpandRecordColumn(Tabela, "Row", {"id", "shopify_order_id", "order_number", "created_at_shopify", "imported_at", "transaction_authorization", "transaction_payment_id", "tags"}, {"id", "shopify_order_id", "order_number", "created_at_shopify", "imported_at", "transaction_authorization", "transaction_payment_id", "tags"}),
				    TiposAjustados = Table.TransformColumnTypes(Expandido, {
				        {"id", Int64.Type},
				        {"shopify_order_id", type text},
				        {"order_number", type text},
				        {"created_at_shopify", type datetimezone},
				        {"imported_at", type datetimezone},
				        {"transaction_authorization", type text},
				        {"transaction_payment_id", type text}
				    })
				in
				    TiposAjustados

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

