table Matrixfy
	lineageTag: 9cb5e33d-b83e-492a-a052-71b3bc096fb4

	column id
		dataType: int64
		formatString: 0
		lineageTag: 5ae44038-0784-47af-b0d2-93c8c2567476
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column shopify_order_id
		dataType: string
		lineageTag: f1c6a7c9-e014-4579-a202-a28a6bc95bbb
		summarizeBy: none
		sourceColumn: shopify_order_id

		annotation SummarizationSetBy = Automatic

	column order_number
		dataType: string
		lineageTag: 76af9e8b-894b-400e-8121-544461cfc33a
		summarizeBy: none
		sourceColumn: order_number

		annotation SummarizationSetBy = Automatic

	column created_at_shopify
		dataType: dateTime
		formatString: General Date
		lineageTag: c698dc72-a193-4293-8662-974192b721f5
		summarizeBy: none
		sourceColumn: created_at_shopify

		variation Variation
			isDefault
			relationship: 5294f2f6-4466-4659-a80f-e88371732c3e
			defaultHierarchy: LocalDateTable_97bfe54d-aae8-4c98-a915-7d7e565e8b3d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column imported_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 465a4e5d-d5dd-4058-bad2-925dfeb8217b
		summarizeBy: none
		sourceColumn: imported_at

		variation Variation
			isDefault
			relationship: abbeca68-bda1-432f-96f5-2e3a2cf44e43
			defaultHierarchy: LocalDateTable_44984a46-fbd8-4df1-ba54-ff178de1a603.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column transaction_authorization
		dataType: string
		lineageTag: 5b89c679-d5b9-4bc0-8769-45464e1e32ec
		summarizeBy: none
		sourceColumn: transaction_authorization

		annotation SummarizationSetBy = Automatic

	column transaction_payment_id
		dataType: string
		lineageTag: 656c1564-f4c2-45ee-b3dc-e6b944f9fef8
		summarizeBy: none
		sourceColumn: transaction_payment_id

		annotation SummarizationSetBy = Automatic

	partition Matrixfy = m
		mode: import
		queryGroup: Marketplaces\Repasses\Shopify
		source =
				let
				    BaseUrl  = "https://mxsdrojeuyuuokfxhjyb.supabase.co",
				    ApiKey   = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14c2Ryb2pldXl1dW9rZnhoanliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MTEwNzEsImV4cCI6MjA4MjM4NzA3MX0.loxFGXbJVk3xwSHb8U5STG6QxoISFtlB6qcQLxowRs8",
				    PageSize = 1000,
				    BuscarPagina = (Offset as number) as list =>
				        Json.Document(Web.Contents(BaseUrl, [
				            RelativePath = "rest/v1/shopify_pedidos_raw",
				            Headers      = [apikey = ApiKey, Authorization = "Bearer " & ApiKey],
				            Query        = [select="*", limit=Text.From(PageSize), offset=Text.From(Offset)]
				        ])),
				    TodasPaginas = List.Generate(
				        () => [Pagina = BuscarPagina(0), Offset = 0],
				        each List.Count([Pagina]) > 0,
				        each [Pagina = BuscarPagina([Offset] + PageSize), Offset = [Offset] + PageSize],
				        each [Pagina]
				    ),
				    TodosRegistros = List.Combine(TodasPaginas),
				    Tabela         = Table.FromList(TodosRegistros, Splitter.SplitByNothing(), {"Row"}),
				    Expandido = Table.ExpandRecordColumn(Tabela, "Row",
				        {"id", "shopify_order_id", "order_number", "created_at_shopify", "imported_at", "transaction_authorization", "transaction_payment_id"},
				        {"id", "shopify_order_id", "order_number", "created_at_shopify", "imported_at", "transaction_authorization", "transaction_payment_id"}),
				    TiposAjustados = Table.TransformColumnTypes(Expandido, {
				        {"id", Int64.Type},
				        {"shopify_order_id", type text},
				        {"order_number", type text},
				        {"created_at_shopify", type datetimezone},
				        {"imported_at", type datetimezone},
				        {"transaction_authorization", type text},
				        {"transaction_payment_id", type text}
				    })
				in
				    TiposAjustados

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

