table 'Over por Período'
	lineageTag: 05716d35-3c36-4842-a81b-4a1369669075

	column id_produto
		dataType: int64
		formatString: 0
		lineageTag: 1863b1d2-1da0-44b1-8556-52c49269e318
		summarizeBy: sum
		sourceColumn: id_produto

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35eaae90-83d6-4fd3-8c89-b057348c027f
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: bc38d4e2-a299-4c72-98de-64d279d758d4
			defaultHierarchy: LocalDateTable_9fe98b23-3630-4941-9a0c-89896458f4eb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column over_frete
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: cdbfb860-55b8-4cb7-a774-d895e279db0b
		summarizeBy: sum
		sourceColumn: over_frete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition 'Over por Período' = m
		mode: import
		queryGroup: SupaBase
		source =
				let
				    BaseUrl  = "https://mxsdrojeuyuuokfxhjyb.supabase.co",
				    ApiKey   = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14c2Ryb2pldXl1dW9rZnhoanliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MTEwNzEsImV4cCI6MjA4MjM4NzA3MX0.loxFGXbJVk3xwSHb8U5STG6QxoISFtlB6qcQLxowRs8",
				    PageSize = 1000,
				
				    BuscarPagina = (Offset as number) as list =>
				        Json.Document(Web.Contents(BaseUrl, [
				            RelativePath = "rest/v1/vw_historico_over_frete",
				            Headers      = [apikey = ApiKey, Authorization = "Bearer " & ApiKey],
				            Query        = [select="*", limit=Text.From(PageSize), offset=Text.From(Offset)]
				        ])),
				
				    TodasPaginas = List.Generate(
				        () => [Pagina = BuscarPagina(0), Offset = 0],
				        each List.Count([Pagina]) > 0,
				        each [Pagina = BuscarPagina([Offset] + PageSize), Offset = [Offset] + PageSize],
				        each [Pagina]
				    ),
				
				    TodosRegistros = List.Combine(TodasPaginas),
				    Tabela         = Table.FromList(TodosRegistros, Splitter.SplitByNothing(), {"Row"}),
				
				    Expandido = Table.ExpandRecordColumn(Tabela, "Row",
				        {"data", "id_produto", "over_frete"},
				        {"data", "id_produto", "over_frete"}),
				
				    TiposAjustados = Table.TransformColumnTypes(Expandido, {
				        {"data", type date},
				        {"id_produto", Int64.Type},
				        {"over_frete", Currency.Type}
				    })
				in
				    TiposAjustados

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

