table 'vw_mlb_daily - ADS-Api-ML'
	lineageTag: d3f2897a-dd18-46dc-83d9-3e6f06f2a0cd

	column item_id
		dataType: string
		lineageTag: 21ed5a01-f4e0-40f5-916d-f5d68d1d3951
		summarizeBy: none
		sourceColumn: item_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7465d13b-24be-44b1-b76f-14d7a9b6376c
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 63fe833c-3d55-4eed-82ba-c5676974338d
			defaultHierarchy: LocalDateTable_cbdb70b5-fef7-496d-9098-4df345dccc01.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column title
		dataType: string
		lineageTag: d3c60c68-da77-48d9-8f2c-b8bfaeda6bb5
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column seller_sku
		dataType: string
		lineageTag: 06e819c7-a49c-47bd-b107-fd2da5931e8a
		summarizeBy: none
		sourceColumn: seller_sku

		annotation SummarizationSetBy = Automatic

	column visits
		dataType: int64
		formatString: 0
		lineageTag: 0e56db46-f2c2-4c1a-adb6-fa740f3fac2b
		summarizeBy: sum
		sourceColumn: visits

		annotation SummarizationSetBy = Automatic

	column units_sold
		dataType: int64
		formatString: 0
		lineageTag: 0ce5de01-0bed-4a30-be41-72bf9eced823
		summarizeBy: sum
		sourceColumn: units_sold

		annotation SummarizationSetBy = Automatic

	column gmv
		dataType: double
		lineageTag: b7812286-20a9-4d2d-a211-ba81fa4af9d7
		summarizeBy: sum
		sourceColumn: gmv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ad_cost
		dataType: double
		lineageTag: f688b5ad-721c-480e-b05d-79b7ea49af37
		summarizeBy: sum
		sourceColumn: ad_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ad_clicks
		dataType: int64
		formatString: 0
		lineageTag: e7114e83-11c8-4764-b908-b5e7e5b6f8d1
		summarizeBy: sum
		sourceColumn: ad_clicks

		annotation SummarizationSetBy = Automatic

	column ad_acos
		dataType: double
		lineageTag: d4ec11cc-dec4-4f5c-ab2a-5f3c886d8009
		summarizeBy: sum
		sourceColumn: ad_acos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ad_roas
		dataType: double
		lineageTag: 56086c49-4811-4db7-9eae-88d37cb9cfed
		summarizeBy: sum
		sourceColumn: ad_roas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column conversion_pct
		dataType: double
		lineageTag: b3e851da-5925-4103-b9a3-5d4eca10385e
		summarizeBy: sum
		sourceColumn: conversion_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column roas_real
		dataType: double
		lineageTag: d8d2b472-66f5-4c75-a438-43304a195756
		summarizeBy: sum
		sourceColumn: roas_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gmv_net_of_ads
		dataType: double
		lineageTag: debda06f-1c1c-4d1a-b744-88bafca8cc13
		summarizeBy: sum
		sourceColumn: gmv_net_of_ads

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'vw_mlb_daily - ADS-Api-ML' = m
		mode: import
		queryGroup: SupaBase
		source = ```
				let
				    BaseUrl  = "https://ssqnthxkzrnhpehugcnj.supabase.co",
				    ApiKey   = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcW50aHhrenJuaHBlaHVnY25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzODQ4MTAsImV4cCI6MjA5NDk2MDgxMH0.U2y7kG5882b4ffQ9--jh29Y0YDi5E-N9fQeZdkaGYyc",
				    
				
				    PageSize = 1000,
				
				    BuscarPagina = (Offset as number) as list =>
				        Json.Document(Web.Contents(BaseUrl, [
				            RelativePath = "rest/v1/vw_mlb_daily",
				            Headers      = [apikey = ApiKey, Authorization = "Bearer " & ApiKey],
				            Query        = [select="*", order="item_id.asc,date.asc", limit=Text.From(PageSize), offset=Text.From(Offset)]
				        ])),
				
				    TodasPaginas = List.Generate(
				        () => [Pagina = BuscarPagina(0), Offset = 0],
				        each List.Count([Pagina]) > 0,
				        each [Pagina = BuscarPagina([Offset] + PageSize), Offset = [Offset] + PageSize],
				        each [Pagina]
				    ),
				
				    TodosRegistros = List.Combine(TodasPaginas),
				    Tabela         = Table.FromList(TodosRegistros, Splitter.SplitByNothing(), {"Row"}),
				
				    Expandido = Table.ExpandRecordColumn(Tabela, "Row",
				        {"item_id","date","title","seller_sku","visits","units_sold","gmv",
				         "ad_cost","ad_clicks","ad_acos","ad_roas","conversion_pct","roas_real","gmv_net_of_ads"},
				        {"item_id","date","title","seller_sku","visits","units_sold","gmv",
				         "ad_cost","ad_clicks","ad_acos","ad_roas","conversion_pct","roas_real","gmv_net_of_ads"}),
				
				    TiposAjustados = Table.TransformColumnTypes(Expandido, {
				        {"item_id",         type text},
				        {"date",            type date},
				        {"title",           type text},
				        {"seller_sku",      type text},
				        {"visits",          Int64.Type},
				        {"units_sold",      Int64.Type},
				        {"gmv",             type number},
				        {"ad_cost",         type number},
				        {"ad_clicks",       Int64.Type},
				        {"ad_acos",         type number},
				        {"ad_roas",         type number},
				        {"conversion_pct",  type number},
				        {"roas_real",       type number},
				        {"gmv_net_of_ads",  type number}
				    })
				in
				    TiposAjustados
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

